services:
  frontend:
    image: urfist/expense_tracker_frontend:0.0.2
    ports:
     - "80:80"
  backend:
    image: urfist/expense_tracker_backend:0.0.2
    environment:
      - DB_PATH=/app/data/expenses.db 
    volumes:
      - .data:/app/data